services:
  sql-database:
    image: mysql/mysql-server
    environment: 
       MYSQL_ROOT_PASSWORD: akhila8mysql
       MYSQL_DATABASE: institution
       MYSQL_USER: root
       MYSQL_PASSWORD: akhila8mysql
    volumes:
       - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    
  tomcat:
     image: alpine-compose
     ports:
      - "8080:8080"
     environment:
       VIRTUAL_HOST: localhost
       VIRTUAL_PORT: 8080
       dbConnectionUrl: jdbc:mysql://sql-database:3306/institution
       dbUsername: root 
       dbPassword: akhila8mysql
     links:
      - sql-database
      
  nginix:
     image: app-angular
     ports:
      - "80:80"
     links:
      - tomcat
      
 
